yhkwak/team_prjt

- bread_project_dev/src/main/java/com/bread/app/controller/MypageController.java
- bread_project_dev/src/main/java/com/bread/app/dao/BakeryDAO.java
- bread_project_dev/src/main/java/com/bread/app/vo/BakeryVO.java
- bread_project_dev/src/main/java/com/bread/service/bakery/BakeryGetService.java
- bread_project_dev/src/main/java/com/bread/service/bakery/BakeryJoinService.java
- bread_project_dev/src/main/java/com/bread/service/bakery/BakeryService.java
- bread_project_dev/src/main/java/com/bread/service/bakery/BakeryUpdateService.java
- bread_project_dev/src/main/resources/config/mybatis-config.xml
- bread_project_dev/src/main/resources/mapper/BakeryMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/shopinfo.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/update.jsp
- bread_project_dev/src/main/webapp/resources/css/shopinfo.css
- bread_project_dev/src/main/webapp/resources/js/shopinfo.js
> 가게 관리 페이지 및 DB연동 까지의 작업

- bread_project_dev/src/main/java/com/bread/app/controller/MemberController.java
- bread_project_dev/src/main/java/com/bread/app/controller/MypageController.java
- bread_project_dev/src/main/java/com/bread/app/vo/MemberVO.java
- bread_project_dev/src/main/java/com/bread/app/vo/NoticeVO.java
- bread_project_dev/src/main/java/com/bread/service/member/MemberService.java
- bread_project_dev/src/main/java/com/bread/service/member/MemberUpdateService.java
- bread_project_dev/src/main/resources/mapper/MemberMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/main.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/member/update.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/search/viewBakery.jsp
- bread_project_dev/src/main/webapp/resources/css/companyProfile.css
companyprofile.css 2 삭제완료
viewBakery.jsp 인스타그램 부분 삭제완료
> 회원정보 이미지 삽입 및 변경에 대한 수정

- bread_project_dev/src/main/resources/mapper/BakeryMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/main.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/orderManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/shopinfo.jsp
- bread_project_dev/src/main/webapp/resources/css/main.css
- bread_project_dev/src/main/webapp/resources/css/orderManagement.css
- bread_project_dev/src/main/webapp/resources/css/update.css
main.css #login_logo_default 추가
main.jsp 첨부파일 넣는 부분 조건식 변경
orderManagement.css, jsp 추가
shopinfo.jsp 네비게이션 프로필 수정 부분 경로 mypage-> member
update.css 박스 위치 중앙으로 이동
update.jsp 경로 변경
viewBakery.css UTF-8 추가
> BakeryMapper 컬럼 변경

- bread_project_dev/src/main/java/com/bread/app/common/FivePageNav.java
- bread_project_dev/src/main/java/com/bread/app/controller/SearchBakeryController.java
- bread_project_dev/src/main/java/com/bread/app/dao/SearchDAO.java
- bread_project_dev/src/main/java/com/bread/app/vo/SearchVO.java
- bread_project_dev/src/main/java/com/bread/service/search/SearchBakeryService.java
- bread_project_dev/src/main/java/com/bread/service/search/SearchPageService.java
- bread_project_dev/src/main/java/com/bread/service/search/SearchService.java
- bread_project_dev/src/main/java/com/bread/service/search/SearchTotalCountService.java
- bread_project_dev/src/main/resources/mapper/SearchMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/member/update.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/search/paging.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/search/searchBakery.jsp
SearchBakery 부분 DB연동 추가
Paging 기능 추가
> SearchBakery 부분 DB연동 추가, Paging 기능 추가

- bread_project_dev/src/main/java/com/bread/app/controller/MemberController.java
- bread_project_dev/src/main/resources/mapper/BreadMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/board/noticeUpdate.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/board/noticeView.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/member/login.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/member/update.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/productManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/productRegister.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/productUpdate.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/shopinfo.jsp
- bread_project_dev/src/main/webapp/resources/js/productRegister.js
login.jsp MemberController 쿠키완료
productRegister유효성검사 작업중
> breadMapper.xml수정

- bread_project_dev/src/main/java/com/bread/app/controller/HomeController.java
- bread_project_dev/src/main/java/com/bread/app/controller/MypageController.java
- bread_project_dev/src/main/webapp/WEB-INF/views/info/accessterms.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/main.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/orderManagement.jsp
- bread_project_dev/src/main/webapp/resources/css/accessterms.css
- bread_project_dev/src/main/webapp/resources/js/update.js
이용약관 페이지 추가
홈 컨트롤러에서 이용약관 페이지 맵핑,
메인페이지 등급별 노출 페이지 추가 및 수정
> 이용약관 페이지 추가

- bread_project_dev/src/main/java/com/bread/app/controller/MypageController.java
- bread_project_dev/src/main/webapp/WEB-INF/views/cart/cartList.jsp
1. MypageController - 페이지 맵핑 : orderList, cartList
2. 기존 cart.jsp 페이지 에서 cartList.jsp 로 바꿔야함
> MypageController, cartList.jsp 수정

- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/productManagement.jsp
- bread_project_dev/src/main/webapp/resources/css/noticeView.css
- bread_project_dev/src/main/webapp/resources/css/productManagement.css
공지사항 상세페이지 css 수정, 상품관리 jsp, css 수정
> 공지사항 상세페이지 css 수정, 상품관리 jsp, css 수정

- bread_project_dev/src/main/java/com/bread/app/controller/MypageController.java
- bread_project_dev/src/main/java/com/bread/app/controller/OrderController.java
- bread_project_dev/src/main/java/com/bread/app/dao/OrderDAO.java
- bread_project_dev/src/main/java/com/bread/app/vo/OrderListVO.java
- bread_project_dev/src/main/java/com/bread/service/order/OrderListViewService.java
- bread_project_dev/src/main/java/com/bread/service/order/OrderService.java
- bread_project_dev/src/main/resources/mapper/OrderMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/orderList.jsp
orderList.jsp 결제상태 출력 - 완료/실패 표시. 날짜 패턴 변환
MypageController.java - orderlist 맵핑한거 삭제
OrderListVO - 내용 추가
신규작성
OrderController.java
OrderMapper.xml
OrderService.java
OrderListViewService.java
OrderDAO.java
> 주문 내역 관련 신규 작성 및 내용 수정

- bread_project_dev/src/main/java/com/bread/app/controller/MemberController.java
- bread_project_dev/src/main/webapp/WEB-INF/views/member/findPw.jsp
- bread_project_dev/src/main/webapp/resources/css/findPw.css
아이디, 비밀번호 찾기 페이지 수정 및 추가, 컨트롤러 페이지 맵핑 추가
> 아이디, 비밀번호 찾기 페이지 수정 및 추가, 컨트롤러 페이지 맵핑 추가

- bread_project_dev/src/main/java/com/bread/app/controller/HomeController.java
- bread_project_dev/src/main/resources/mapper/ReviewMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/info/faq.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/main.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/orderList.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/orderManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/productManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/productRegister.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/productUpdate.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/shopinfo.jsp
- bread_project_dev/src/main/webapp/resources/css/accessterms.css
- bread_project_dev/src/main/webapp/resources/css/faq.css
- bread_project_dev/src/main/webapp/resources/css/join.css
- bread_project_dev/src/main/webapp/resources/css/login.css
- bread_project_dev/src/main/webapp/resources/css/order.css
- bread_project_dev/src/main/webapp/resources/css/orderManagement.css
- bread_project_dev/src/main/webapp/resources/css/productManagement.css
- bread_project_dev/src/main/webapp/resources/css/productRegister.css
- bread_project_dev/src/main/webapp/resources/css/productUpdate.css
- bread_project_dev/src/main/webapp/resources/css/shopinfo.css
- bread_project_dev/src/main/webapp/resources/css/update.css
faq 추가 및 크기 수정, 배치, 테두리 색상 gray-> lightgray로 일부 수정
> faq 추가 및 크기 수정, 배치, 테두리 색상 gray-> lightgray로 일부 수정

- bread_project_dev/src/main/webapp/WEB-INF/views/board/notice.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/member/login.jsp
- bread_project_dev/src/main/webapp/resources/css/findId.css
- bread_project_dev/src/main/webapp/resources/css/findPw.css
- bread_project_dev/src/main/webapp/resources/css/notice.css
아이디, 비밀번호 찾기 css 수정, 공지사항 jsp css 수정 중 / 로그인 페이지 경로 추가
> 아이디, 비밀번호 찾기 css 수정, 공지사항 jsp css 수정 중 / 로그인 페이지 경로 추가

- bread_project_dev/src/main/webapp/WEB-INF/views/member/findId.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/member/findPw.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/orderList.jsp
- bread_project_dev/src/main/webapp/resources/css/findId.css
- bread_project_dev/src/main/webapp/resources/css/findPw.css
- bread_project_dev/src/main/webapp/resources/css/order.css
진짜 찐으로 마지막 아이디, 비밀번호 css jsp 수정 orderList.jsp, css 수정 중
> 진짜 찐으로 마지막 아이디, 비밀번호 css jsp 수정 orderList.jsp, css 수정 중

- bread_project_dev/src/main/java/com/bread/app/controller/OrderController.java
- bread_project_dev/src/main/java/com/bread/app/dao/OrderDAO.java
- bread_project_dev/src/main/java/com/bread/app/vo/OrderListVO.java
- bread_project_dev/src/main/java/com/bread/service/order/OrderListViewService.java
- bread_project_dev/src/main/java/com/bread/service/order/OrderPageService.java
- bread_project_dev/src/main/java/com/bread/service/order/OrderService.java
- bread_project_dev/src/main/java/com/bread/service/order/OrderTotalCountService.java
- bread_project_dev/src/main/resources/mapper/OrderMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/orderList.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/paging.jsp
페이징 관련 내용 수정
/OrderController.java
/OrderDAO.java
/OrderListVO.java
/OrderListViewService.java
/OrderService.java (내용없음) 쏘리
페이징 관련 신규 추가
/OrderPageService.java
/OrderTotalCountService.java
/OrderMapper.xml/orderList.jsp/paging.jsp
> 페이징 관련 추가 및 수정

- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/orderList.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/search/viewBakery.jsp
- bread_project_dev/src/main/webapp/resources/css/order.css
- bread_project_dev/src/main/webapp/resources/css/viewBakery.css
> 빵집 상세보기, 오더 리스트 수정

- bread_project_dev/src/main/webapp/WEB-INF/views/board/notice.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/board/noticeUpdate.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/board/noticeView.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/board/noticeWrite.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/productManagement.jsp
- bread_project_dev/src/main/webapp/resources/css/notice.css
- bread_project_dev/src/main/webapp/resources/css/noticeUpdate.css
- bread_project_dev/src/main/webapp/resources/css/noticeView.css
- bread_project_dev/src/main/webapp/resources/css/noticeWrite.css
- bread_project_dev/src/main/webapp/resources/css/productManagement.css
- bread_project_dev/src/main/webapp/resources/js/noticeWrite.js
> 대략적인 공지사항 내용 수정 및 추가사항

- bread_project_dev/src/main/java/com/bread/app/controller/OrderController.java
- bread_project_dev/src/main/java/com/bread/app/dao/OrderDAO.java
- bread_project_dev/src/main/java/com/bread/app/vo/OrderListVO.java
- bread_project_dev/src/main/java/com/bread/app/vo/PageVO.java
- bread_project_dev/src/main/java/com/bread/service/order/OrderListViewService.java
- bread_project_dev/src/main/java/com/bread/service/order/OrderService.java
- bread_project_dev/src/main/java/com/bread/service/order/OrderTotalCountService.java
- bread_project_dev/src/main/resources/config/mybatis-config.xml
- bread_project_dev/src/main/resources/mapper/OrderMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/orderList.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/paging.jsp
OrderCountroller
OrderDAO
PageVO.java
OrderListVO
OrdeTotalCountService
OrderListViewService
OrderService
mybatis-config.xml
OrderMapper
paging.jsp
orderList.jsp
> 구매내역 관련 수정사항

- bread_project_dev/src/main/java/com/bread/app/controller/AdminMemController.java
- bread_project_dev/src/main/java/com/bread/app/dao/AdminMemDAO.java
- bread_project_dev/src/main/java/com/bread/app/vo/SearchVO.java
- bread_project_dev/src/main/java/com/bread/service/adminMembership/AdminMemDelService.java
- bread_project_dev/src/main/java/com/bread/service/adminMembership/AdminMemListService.java
- bread_project_dev/src/main/java/com/bread/service/adminMembership/AdminMemPageService.java
- bread_project_dev/src/main/java/com/bread/service/adminMembership/AdminMemService.java
- bread_project_dev/src/main/java/com/bread/service/adminMembership/AdminMemTotalCountService.java
- bread_project_dev/src/main/java/com/bread/service/adminMembership/AdminMemUpdateService.java
- bread_project_dev/src/main/resources/mapper/AdminMemMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/admin/AdminMemManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/admin/AdminPaging.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/main.jsp
- bread_project_dev/src/main/webapp/resources/css/AdminMemManagement.css
신규작성
AdminMemController.java
AdminMemDAO.java
AdminMemService.java
AdminMemDelService.java
AdminMemListService.java
AdminMemPageService.java
AdminMemTotalCountService.java
AdminMemUpdateService.java
AdminMemMapper.xml
AdminMemManagement.css
AdminMemManagement.jsp
AdminPaging.jsp
부분 수정
SearchVO - 객체추가
main.jsp - 관리자페이지 맵핑
> 관리자페이지 - 회원관리 관련 신규작성 및 수정사항

- bread_project_dev/src/main/java/com/bread/app/controller/AdminMemController.java
- bread_project_dev/src/main/java/com/bread/app/controller/AdminStoreController.java
- bread_project_dev/src/main/java/com/bread/app/controller/AjaxController.java
- bread_project_dev/src/main/java/com/bread/app/dao/AdminMemDAO.java
- bread_project_dev/src/main/java/com/bread/app/dao/AdminStoreDAO.java
- bread_project_dev/src/main/java/com/bread/service/adminMembership/AdminMemDelService.java
- bread_project_dev/src/main/java/com/bread/service/adminMembership/AdminMemUpdateService.java
- bread_project_dev/src/main/java/com/bread/service/adminStore/AdminStoreDelService.java
- bread_project_dev/src/main/java/com/bread/service/adminStore/AdminStoreListService.java
- bread_project_dev/src/main/java/com/bread/service/adminStore/AdminStorePageService.java
- bread_project_dev/src/main/java/com/bread/service/adminStore/AdminStoreService.java
- bread_project_dev/src/main/java/com/bread/service/adminStore/AdminStoreTotalCountService.java
- bread_project_dev/src/main/resources/mapper/AdminMemMapper.xml
- bread_project_dev/src/main/resources/mapper/AdminStoreMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/admin/AdminMemManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/admin/AdminMemPaging.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/admin/AdminStoreManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/admin/AdminStorePaging.jsp
관리자페이지 - 회원관리 관련 수정사항
AjaxController.java 내용추가
AdminMemController.java
AdminMemDAO.java
AdminMemService.java
AdminMemDelService.java
AdminMemUpdateService.java
AdminMemMapper.xml
AdminMemManagement.jsp
AdminMemPaging.jsp 이름변경 내용수정
관리자페이지 - 매장관리 관련 신규작성
AdminStoreController.java
AdminStoreDAO.java
AdminStoreService.java
AdminStoreListService.java
AdminStorePageService.java
AdminStoreDelService.java
AdminStoreUpdateService.java
AdminStoreTotalCountService.java
AdminStoreMapper.xml
AdminStoreManagement.jsp
AdminStorePaging.jsp
> 관리자페이지 - 회원관리/ 매장관리 관련 신규 작성 및 수정사항

- bread_project_dev/src/main/webapp/WEB-INF/views/cart/cart.jsp
- bread_project_dev/src/main/webapp/resources/css/cart.css
> cart.jsp, css 수정

- bread_project_dev/src/main/webapp/WEB-INF/views/cart/cart.jsp
> jsp 오류 수정..

- bread_project_dev/src/main/webapp/WEB-INF/views/cart/cart.jsp
- bread_project_dev/src/main/webapp/resources/css/cart.css
> 진짜 확인도 다했습니다 찐막 오류 수정.

- bread_project_dev/src/main/java/com/bread/app/controller/MemberController.java
- bread_project_dev/src/main/java/com/bread/app/dao/MemberDAO.java
- bread_project_dev/src/main/java/com/bread/service/member/MemberFindIdService.java
- bread_project_dev/src/main/java/com/bread/service/member/MemberService.java
- bread_project_dev/src/main/resources/mapper/MemberMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/member/findId.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/member/findIdResult.jsp
- bread_project_dev/src/main/webapp/resources/css/findIdResult.css
> 아이디 찾기 서비스

- bread_project_dev/src/main/webapp/WEB-INF/views/cart/cart.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/member/findIdResult.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/search/viewBakery.jsp
- bread_project_dev/src/main/webapp/resources/css/cart.css
- bread_project_dev/src/main/webapp/resources/css/findIdResult.css
- bread_project_dev/src/main/webapp/resources/css/viewBakery.css
viewBakery.jsp, css 부분 수정 cart.jsp - 버튼 추가, cart.css - 버튼 css / findIdResult.jsp, css 수정 /
> cart.jsp - 버튼 추가, cart.css - 버튼 css / findIdResult.jsp, css 수정 /

- bread_project_dev/src/main/webapp/WEB-INF/views/admin/AdminMemManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/admin/AdminMemPaging.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/admin/AdminStoreManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/admin/AdminStorePaging.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/admin/adminProductManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/admin/adminProductUpdate.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/common/header.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/member/update.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/search/searchBakery.jsp
- bread_project_dev/src/main/webapp/resources/css/AdminMemManagement.css
- bread_project_dev/src/main/webapp/resources/css/AdminStoreManagement.css
- bread_project_dev/src/main/webapp/resources/css/adminProductManagement.css
- bread_project_dev/src/main/webapp/resources/css/adminProductUpdate.css
- bread_project_dev/src/main/webapp/resources/css/notice.css
- bread_project_dev/src/main/webapp/resources/css/searchBakery.css
- bread_project_dev/src/main/webapp/resources/css/update.css
관리자페이지 CSS, 헤더 수정, 빵집 목록 페이지 수정
> 관리자페이지 CSS, 헤더 수정, 빵집 목록 페이지 수정

- bread_project_dev/src/main/webapp/WEB-INF/views/admin/adminProductManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/admin/adminProductPaging.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/cart/payment_complete.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/shopinfo.jsp
- bread_project_dev/src/main/webapp/resources/css/adminProductManagement.css
- bread_project_dev/src/main/webapp/resources/css/payment_complete.css
- bread_project_dev/src/main/webapp/resources/css/searchBakery.css
- bread_project_dev/src/main/webapp/resources/css/shopinfo.css
> 구매완료 페이지 수정 및 관리자 상품관리 페이지 보완

- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/orderList.jsp
- bread_project_dev/src/main/webapp/resources/css/order.css
> order.jsp, css 수정

- bread_project_dev/src/main/java/com/bread/app/controller/AjaxController.java
- bread_project_dev/src/main/java/com/bread/app/controller/BoardController.java
- bread_project_dev/src/main/java/com/bread/app/controller/MemberController.java
- bread_project_dev/src/main/java/com/bread/app/dao/MemberDAO.java
- bread_project_dev/src/main/java/com/bread/app/dao/NoticeDAO.java
- bread_project_dev/src/main/java/com/bread/app/vo/SearchVO.java
- bread_project_dev/src/main/java/com/bread/service/notice/NoticeService.java
- bread_project_dev/src/main/java/com/bread/service/notice/NoticeTotalCountService.java
- bread_project_dev/src/main/resources/mapper/MemberMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/member/login.jsp
- bread_project_dev/src/main/webapp/resources/js/join.js
> 회원가입 전화번호 유효성검사 추가 가입완료, notice totalcount다르게 나오는 문제 해결, 로그인 비밀번호

- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/orderList.jsp
- bread_project_dev/src/main/webapp/resources/css/order.css
> orderList.jsp, css 수정

- bread_project_dev/src/main/webapp/WEB-INF/views/board/notice.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/board/paging.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/common/navigation.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/map/map.jsp
- bread_project_dev/src/main/webapp/resources/css/AdminMemManagement.css
- bread_project_dev/src/main/webapp/resources/css/AdminStoreManagement.css
- bread_project_dev/src/main/webapp/resources/css/adminProductManagement.css
- bread_project_dev/src/main/webapp/resources/css/adminProductUpdate.css
- bread_project_dev/src/main/webapp/resources/css/cart.css
- bread_project_dev/src/main/webapp/resources/css/map.css
- bread_project_dev/src/main/webapp/resources/css/notice.css
- bread_project_dev/src/main/webapp/resources/css/productManagement.css
- bread_project_dev/src/main/webapp/resources/css/productRegister.css
- bread_project_dev/src/main/webapp/resources/css/shopinfo.css
- bread_project_dev/src/main/webapp/resources/css/update.css
- bread_project_dev/src/main/webapp/resources/js/map.js
빵집 지도 구성 및 CSS 수정, 네비게이션 분리 JSP 추가(아직 페이지 별 적용은 x),마이페이지,관리자페이지 에니메이션 추가
> 빵집 지도 구성 및 CSS 수정, 네비게이션 분리 JSP 추가(아직 페이지 별 적용은 x),마이페이지,관리자페이지 에니메이션 추가

- bread_project_dev/src/main/webapp/WEB-INF/views/cart/cart.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/common/navigation.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/member/update.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/orderList.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/orderManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/paging.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/paging2.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/productManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/shopinfo.jsp
- bread_project_dev/src/main/webapp/resources/css/order.css
- bread_project_dev/src/main/webapp/resources/css/orderManagement.css
네비게이션 수정, 주문관리 및 구매내역 CSS 수정 및 보완
> 네비게이션 수정, 주문관리 및 구매내역 CSS 수정 및 보완

- bread_project_dev/src/main/java/com/bread/app/controller/MemberController.java
- bread_project_dev/src/main/java/com/bread/app/dao/MemberDAO.java
- bread_project_dev/src/main/java/com/bread/service/member/MemberChangePwService.java
- bread_project_dev/src/main/java/com/bread/service/member/MemberService.java
- bread_project_dev/src/main/resources/mapper/MemberMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/member/findPwResult.jsp
- bread_project_dev/src/main/webapp/resources/css/findId.css
- bread_project_dev/src/main/webapp/resources/css/findPwResult.css
> 비밀번호 찾기 구현

- bread_project_dev/src/main/java/com/bread/app/controller/SearchBakeryController.java
- bread_project_dev/src/main/java/com/bread/app/dao/LikesDAO.java
- bread_project_dev/src/main/java/com/bread/app/vo/LikesVO.java
- bread_project_dev/src/main/java/com/bread/service/likes/LikesAddService.java
- bread_project_dev/src/main/java/com/bread/service/likes/LikesCheckService.java
- bread_project_dev/src/main/java/com/bread/service/likes/LikesService.java
- bread_project_dev/src/main/resources/config/mybatis-config.xml
- bread_project_dev/src/main/resources/mapper/LikesMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/search/viewBakery.jsp
추가작성
SearchBakeryController / mybatis-config/ viewBakery
신규작성
LikesDAO/LikesVO/LikesService/LikesCheckService/LikesAddService/LikesMapper
> 매장 찜하기 구현 1차

- bread_project_dev/src/main/java/com/bread/app/controller/SearchBakeryController.java
- bread_project_dev/src/main/java/com/bread/app/dao/LikesDAO.java
- bread_project_dev/src/main/java/com/bread/service/likes/LikesAddService.java
- bread_project_dev/src/main/java/com/bread/service/likes/LikesCheckService.java
- bread_project_dev/src/main/java/com/bread/service/likes/LikesService.java
- bread_project_dev/src/main/resources/mapper/LikesMapper.xml
추가 작성 likesService/LikesCheckService/LikesAddService/LikesMapper/LikesDAO/SearchBakeryController
> 매장 찜 구현 2차 수정

- bread_project_dev/src/main/java/com/bread/app/controller/AjaxController.java
- bread_project_dev/src/main/java/com/bread/app/controller/SearchBakeryController.java
- bread_project_dev/src/main/java/com/bread/app/dao/LikesDAO.java
- bread_project_dev/src/main/java/com/bread/service/likes/LikesDelService.java
- bread_project_dev/src/main/resources/mapper/LikesMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/search/viewBakery.jsp
추가수정
AjaxController/ SearchBakeryController/ LikesDAO/ LikesAddService/ LikesMapper/ viewBakery
신규작성
LikesDelService
> 매장찜 구현 3차수정

- bread_project_dev/src/main/java/com/bread/app/controller/AjaxController.java
- bread_project_dev/src/main/java/com/bread/app/controller/MemberController.java
- bread_project_dev/src/main/resources/mapper/MemberMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/member/findId.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/member/findPw.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/member/findPwResult.jsp
- bread_project_dev/src/main/webapp/resources/js/findId.js
- bread_project_dev/src/main/webapp/resources/js/findPw.js
- bread_project_dev/src/main/webapp/resources/js/findPwResult.js
아이디 비밀번호 관련 ajax 작업(아이디 찾기, 비밀번호 찾기-완료, 비밀번호 변경-미완)
> 아이디 비밀번호 관련 ajax 작업(아이디 찾기, 비밀번호 찾기-완료, 비밀번호 변경-미완)

- bread_project_dev/src/main/java/com/bread/service/likes/LikesService.java
> 매장 찜하기 추가수정

- bread_project_dev/src/main/java/com/bread/app/controller/MypageController.java
- bread_project_dev/src/main/java/com/bread/app/controller/SearchBakeryController.java
- bread_project_dev/src/main/java/com/bread/app/dao/LikesDAO.java
- bread_project_dev/src/main/java/com/bread/app/vo/LikesVO.java
- bread_project_dev/src/main/java/com/bread/service/likes/LikeListService.java
- bread_project_dev/src/main/java/com/bread/service/likes/LikePageService.java
- bread_project_dev/src/main/java/com/bread/service/likes/LikesService.java
- bread_project_dev/src/main/java/com/bread/service/likes/LikesTotalCountService.java
- bread_project_dev/src/main/resources/mapper/LikesMapper.xml
- bread_project_dev/src/main/resources/mapper/MemberMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/admin/AdminStoreManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/common/navigation.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/likeList.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/paging3.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/search/viewBakery.jsp
내용추가
LikesMapper/ LikesDAO
LikesService/ LikeListService/ LikesPageService/ LikesTotalCountService
MyPageController/ LikesVO
navigation.jsp/ paging3.jsp/ viewBakery.jap / AdminStoreManagement.jsp
SearchBakeryController < 변경내용 없고 syso 부분만 삭제함
신규작성
likeList.jsp
MemberMapper    :     where -> and 로 내가 걍 고쳐놨음
> 매장찜 관련 최종수정

- bread_project_dev/src/main/webapp/WEB-INF/views/board/notice.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/cart/payment_complete.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/main.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/mypage/productManagement.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/review/reviewWrite.jsp
- bread_project_dev/src/main/webapp/resources/css/login.css
- bread_project_dev/src/main/webapp/resources/css/main.css
- bread_project_dev/src/main/webapp/resources/css/productManagement.css
- bread_project_dev/src/main/webapp/resources/css/reviewWrite.css
- bread_project_dev/src/main/webapp/resources/js/join.js
- bread_project_dev/src/main/webapp/resources/js/update.js
전체적인 CSS 수정 작업, 메인페이지 (후기보러가기 -> 리뷰보러가기)
> 전체적인 CSS 수정 작업, 메인페이지 (후기보러가기 -> 리뷰보러가기)

- bread_project_dev/src/main/java/com/bread/app/controller/ReviewController.java
- bread_project_dev/src/main/webapp/resources/js/reviewWrite.js
ReviewController / reviewWrite.js
불필요한 부분만 삭제
> 리뷰 작성 페이지 수정

- bread_project_dev/src/main/webapp/WEB-INF/views/member/findPwResult.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/review/review.jsp
- bread_project_dev/src/main/webapp/resources/css/findPwResult.css
- bread_project_dev/src/main/webapp/resources/css/review.css
findPwResult.jsp, css 수정 / review.jsp , css 수정
> findPwResult.jsp, css 수정 / review.jsp , css 수정

- bread_project_dev/src/main/java/com/bread/app/dao/LikesDAO.java
- bread_project_dev/src/main/java/com/bread/app/vo/ReviewVO.java
- bread_project_dev/src/main/resources/mapper/LikesMapper.xml
- bread_project_dev/src/main/resources/mapper/SearchMapper.xml
- bread_project_dev/src/main/webapp/WEB-INF/views/review/review.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/search/viewBakery.jsp
LikesDAO /ReviewVO/ LikesMapper/ SearchMapper/ review.jsp/ viewBakery.jsp
> 후기게시판 수정 완료 및 불필요 코드 정리

- bread_project_dev/src/main/webapp/WEB-INF/views/review/reviewWrite.jsp
- bread_project_dev/src/main/webapp/resources/css/reviewWrite.css
reviewWrite.jsp, css 에디터 오류 수정
> reviewWrite.jsp, css 에디터 오류 수정

- bread_project_dev/src/main/webapp/resources/css/review.css
> 삭제버튼 css 수정

- bread_project_dev/src/main/webapp/WEB-INF/views/review/review.jsp
> 후기게시판 삭제버튼 관련 수정

- bread_project_dev/src/main/webapp/WEB-INF/views/review/review.jsp
- bread_project_dev/src/main/webapp/resources/css/review.css
> review.jsp 글씨체 및 크기 수정

- bread_project_dev/src/main/webapp/WEB-INF/views/search/viewBakery.jsp
- bread_project_dev/src/main/webapp/resources/css/viewBakery.css
등록된 상품 없을시 표시글 css 수정, 하트 이미지 위치 조정
> 등록된 상품 없을시 표시글 css 수정, 하트 이미지 위치 조정

- bread_project_dev/src/main/webapp/WEB-INF/views/review/review.jsp
- bread_project_dev/src/main/webapp/WEB-INF/views/search/viewBakery.jsp
- bread_project_dev/src/main/webapp/resources/css/review.css
리뷰 모달창 script 추가 및 css 수정, viewBakery 찜 이미지 사진 경로 변경
> 리뷰 모달창 script 추가 및 css 수정, viewBakery 찜 이미지 사진 경로 변경

- bread_project_dev/src/main/webapp/resources/css/reviewWrite.css
> 리뷰작성 CSS 첨부파일 이미지 위치 수정

- bread_project_dev/src/main/webapp/resources/css/findPwResult.css
> 아이디찾기 위치 css 수정
